version: '3.8'
services:
  rabbitmq1:
    image: rabbitmq:management
    hostname: rabbitmq1
    container_name: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - /opt/docker_volume/rabbitmq/rabbitmq1/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=123
      - RABBITMQ_NODENAME=r1
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:management
    hostname: rabbitmq2
    container_name: rabbitmq2
    ports:
      - "5672:5672"
    # volumes:
    #   - /opt/docker_volume/rabbitmq/rabbitmq2/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=123
      - RABBITMQ_NODENAME=rabbitmq2
      - RABBITMQ_CLUSTERED=true
      - RABBITMQ_CLUSTER_WITH=r1@rabbitmq1
      - RABBITMQ_RAM_NODE=true
    networks:
      - rabbitmq
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5672:5672"
    # volumes:
    #   - /opt/docker_volume/rabbitmq/rabbitmq3/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=123
      - RABBITMQ_NODENAME=rabbitmq3
      - RABBITMQ_CLUSTERED=true
      - RABBITMQ_CLUSTER_WITH=r1@rabbitmq1
      - RABBITMQ_RAM_NODE=true
    networks:
      - rabbitmq
    depends_on:
      - rabbitmq1  

networks:
  rabbitmq:
    driver: bridge

